# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 新入生のためのC言語チュートリアル2017（苫高専ソフテク部）
email: takuya.mk96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  苫小牧高専ソフトウェアテクノロジー部1年生向けのC言語チュートリアル。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tnct-softech2017.github.io" # the base hostname & protocol for your site
permalink: /c-tutorial/:title.html
twitter_username: mktakuya
github_username:  mktakuya

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
